<div id="quickmenu" data-bind="scope: 'quickmenu'">
  <!-- ko template: getTemplate() -->
  <!-- /ko -->

  <!-- Devemos passar o ID da div acima como parâmetro aqui em baixo. -->
  <script type="text/x-magento-init">
    {
      "#quickmenu": {
        "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout(); ?>
      }
    }
  </script>

  <script>
    window.quickMenuItems = <?= $this->getQuickMenuItems() ?>;
    window.quickMenuConfig = <?= $this->getQuickMenuConfigurations() ?>;
  </script>

  <script>
    require([
      'mage/url',
      'Magento_Ui/js/block-loader'
    ], function(url, blockLoader) {
      blockLoader("<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>");
      return url.setBaseUrl('<?php /* @escapeNotVerified */ echo $block->getBaseUrl(); ?>');
    })
  </script>
</div>