<div id="speed_dial" data-bind="scope: 'speed_dial'">
  <!-- ko template: getTemplate() -->
  <!-- /ko -->

  <!-- Devemos passar o ID da div acima como parâmetro aqui em baixo. -->
  <script type="text/x-magento-init">
    {
      "#speed_dial": {
        "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout(); ?>
      }
    }
  </script>

  <script>
    window.speedDialItems = <?= $this->getSpeedDialItems() ?>;
    window.speedDialConfig = <?= $this->getSpeedDialConfigurations() ?>;
  </script>

  <script>
    require([
      'mage/url',
      'Magento_Ui/js/block-loader'
    ], function(url, blockLoader) {
      blockLoader("<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>");
      return url.setBaseUrl('<?php /* @escapeNotVerified */ echo $block->getBaseUrl(); ?>');
    })
  </script>
</div>